name: "Hello World Action"

on: [push]

jobs:
  test_custom_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: myCompositeAction
        uses: Colin-Yeo/GitHubActions@v2
      - run: echo "Bye bye"
        shell: bash
