name: Print "{REPO} says HelloWorld"
on:
  push:
    tags:
      - "colin*"

jobs:
  test_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: myCompositeAction
        uses: Colin-Yeo/GitHubActions@v3
        with:
          repo: 'GitHubActions'
