name: 'Hello World Action'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: myCompositeAction
        uses: Colin-Yeo/GitHubActions@v1
      - run: echo "Bye bye"
        shell: bash
